### PR TITLE
[ui] adds sorted balances to peg listing and select token dialogues

### PR DESCRIPTION
**Pull request by thomasdavis**

### CODE REVIEW

**Comment by 59023g** [comment]
This functionally looks good. I cc'd @j-kappa to give it a quick design cycle. Also, will you write an e2e test for it?

**Comment by 59023g** [comment]
This looks better but doesn't sort

**Comment by thomasdavis** [comment]
Seems to work locally but not on sandpoint, I have been working on it.

**Comment by 59023g** [comment]
Screen Shot 2021-04-28 at 10 33 10 AM
Still no dice

**Review by 59023g — APPROVED** [review]
🧞‍♂️

**Pull request merged**
