### PR TITLE
fix double add of debt on swap

### PR DESCRIPTION
**Pull request by timlind**

### CODE REVIEW

**Comment by canercandan** [comment]
# Test of the CLP module wallet invariant checkers

tested against v1.0-beta.11 (betanet version) with the swap one fix from this PR:

## :heavy_check_mark: Swap Rowan to CUSDC while margin position on
* no monetary policy on
* cusdc pool enabled for margin
* open cusdc position
* swap rowan to cusdc
* does not throw any invariant error

## :heavy_check_mark: Swap CUSDC to Rowan while margin position on
* no monetary policy on
* cusdc pool enabled for margin
* open cusdc position
* swap cusdc to rowan
* does not throw any invariant error

## :heavy_check_mark: Swap CUSDC to CETH while margin position on
* no monetary policy on
* cusdc pool enabled for margin
* open cusdc position
* swap cusdc to rowan
* does not throw any invariant error

## :heavy_check_mark: Swap CETH to CUSDC while margin position on
* no monetary policy on
* cusdc pool enabled for margin
* open cusdc position
* swap cusdc to rowan
* does not throw any invariant error

## :heavy_check_mark: Add liquidity to CUSDC while margin position on
* no monetary policy on
* cusdc pool enabled for margin
* open cusdc position
* add liquidity to USDC pool
* does not throw any invariant error

## :heavy_check_mark: Remove liquidity from CUSDC while margin position on
* no monetary policy on
* cusdc pool enabled for margin
* open cusdc position
* remove liquidity from USDC pool
* does not throw any invariant error

## :heavy_check_mark: LPD from CUSDC while margin position on
* no Rewards or LIQP on
* cusdc pool enabled for margin
* open cusdc position
* enable LPD distribution to distribute at each block
* does not throw any invariant error

## :heavy_check_mark: Rewards to CUSDC while margin position on
* no LPD or LIQP on
* cusdc pool enabled for margin
* open cusdc position
* enable Rewards to CUSDC pool
* does not throw any invariant error

## :heavy_check_mark: Rewards + LPD on while margin position on
* no LIQP on
* cusdc pool enabled for margin
* open cusdc position
* enable LPD distribution to distribute at each block
* enable Rewards to CUSDC pool
* does not throw any invariant error

**Review by canercandan — APPROVED** [review]
LGTM

**Review by canercandan — APPROVED** [review]
LGTM

**Review by AustinoBombino — APPROVED** [review]

**Comment by canercandan** [comment]
CLP wallet aligned with pools:

```
./check-clp-wallet.mjs -p localnet --pool cusdc
height          pool ext        clp ext         diff ext	pool nat	clp nat		diff nat
114		510815.35	510815.35	0.00      	97491029.88	97491029.88	0.00
113		510815.35	510815.35	0.00      	97539549.87	97539549.87	0.00
112		510815.35	510815.35	0.00      	97588094.24	97588094.24	0.00
111		510815.35	510815.35	0.00      	97636663.93	97636663.93	0.00
110		510815.35	510815.35	0.00      	97685258.03	97685258.03	0.00
109		510815.35	510815.35	0.00      	97733876.56	97733876.56	-0.00
108		510815.35	510815.35	0.00      	97782519.52	97782519.52	-0.00
107		510815.35	510815.35	0.00      	97782519.52	97782519.52	-0.00
106		510815.35	510815.35	0.00      	97782519.54	97782519.54	0.00
105		510815.35	510815.35	0.00      	97782519.55	97782519.55	0.00
104		510815.35	510815.35	0.00      	97782519.55	97782519.55	0.00
103		510815.35	510815.35	0.00      	97782519.56	97782519.56	0.00
102		510815.35	510815.35	0.00      	97782519.56	97782519.56	-0.00
101		509815.35	509815.35	0.00      	97593803.08	97593803.08	-0.00
100		509815.35	509815.35	0.00      	97593803.09	97593803.09	-0.00
99		509815.35	509815.35	0.00      	97593803.09	97593803.09	0.00
98		510340.79	510340.79	0.00      	97493803.10	97493803.10	0.00
97		510340.79	510340.79	0.00      	97493803.11	97493803.11	-0.00
96		510340.79	510340.79	0.00      	97493803.11	97493803.11	0.00
95		510340.79	510340.79	0.00      	97493803.12	97493803.12	0.00
94		510340.79	510340.79	0.00      	97493803.12	97493803.12	-0.00
93		510340.79	510340.79	0.00      	97493803.13	97493803.13	-0.00
92		509340.79	509340.79	0.00      	97683152.50	97683152.50	0.00
91		509340.79	509340.79	0.00      	97683152.51	97683152.51	0.00
90		509340.79	509340.79	0.00      	97683152.51	97683152.51	0.00
89		509340.79	509340.79	0.00      	97683152.52	97683152.52	0.00
```

**Pull request merged**
