### PR TITLE
[ChainOps] Ethereum full node deployment

### PR DESCRIPTION
**Pull request by ilchebedelovski**

### CODE REVIEW

**Review by utx0 — APPROVED** [review]
LGTM. @intl-man ill leave this for you to also review and then merge.

**Comment by ElliotFriedman** [comment]
Do you have things configured to connect to ropsten? We will need a ropsten configuration so that we can test using this on testnet.

**Review by ElliotFriedman — CHANGES_REQUESTED** [review]
Could you please also add a configuration for connecting to ropsten?

**Comment by ElliotFriedman** [comment]
Looking at the dashboard, it said it was running an unstable version of geth. I think we should roll back to a LTS or stable version of geth so that we don't hit reliability issues as eth nodes are notorious for crashing. 

Geth/v1.9.25-unstable-d7a64dc0-20201203/linux-amd64/go

Screen Shot 2020-12-07 at 11 36 59 AM

**Comment by ilchebedelovski** [comment]
@ElliotFriedman the `netowrkId` is configurable now, we can set it up in the deploy command:

```
rake cluster:ethnode:deploy[dev,aws,ethereum/client-go,v1.9.24,3]
```

Is the `networkId` enough for connection to Ropsten?

(I have also added arguments for the image and the image tag)

**Comment by intl-man** [comment]
> @ElliotFriedman the `netowrkId` is configurable now, we can set it up in the deploy command:
> 
> ```
> rake cluster:ethnode:deploy[dev,aws,ethereum/client-go,v1.9.24,3]
> ```
> 
> Is the `networkId` enough for connection to Ropsten?
> 
> (I have also added arguments for the image and the image tag)

Looks like this has broken the build @ilchebedelovski ?

**Review by utx0 — APPROVED** [review]
Prefect.

**Comment by utx0** [comment]
Hey @intl-man looks like we didnt end up using this code in the end? Should we just close this out now?

**Pull request closed without merging**
