### PR TITLE
Update siftool

### PR DESCRIPTION
**Pull request by jzvikart**
This PR includes:
- fixes and readme for running siftool on Ubuntu
- backport of siftool changes from future/peggy2 (load testing)

### CODE REVIEW

**Review by sheokapr — APPROVED** [review]
Looks fine to me

**Review by khdegraaf — APPROVED** [review]
LGTM

**Comment by jzvikart** [comment]
Gitleaks disabled, I suppose it makes sense to also disable it on `future/peggy2`?

**Comment by jzvikart** [comment]
Added some more fixes for running on macOS and for connecting to Peggz2 on Tempnet.

**Pull request merged**
