### PR TITLE
Show separate message for out of gas errors

### PR DESCRIPTION
**Pull request by iverc**

### CODE REVIEW

**Review by 59023g — CHANGES_REQUESTED** [review]
The notification shows. But the updated confirmation screen is not showing. It disappears. I should transition to the failed state confirmation screen

https://user-images.githubusercontent.com/5235538/110044146-7ff0f500-7cfd-11eb-9dfd-2d2d96bd290e.mov

**Comment by 59023g** [comment]
I still do not see the "transaction rejected" message in the confirmation modal.

**Comment by iverc** [comment]
@59023g it should not be "rejected" it should say "transaction failed" and that's what it does. please approve.

**Comment by iverc** [comment]
@caseyturnerarrington actually since we verified it works as expected, could you please approve? thanks

**Review by caseyturnerarrington — DISMISSED** [review]

**Comment by caseyturnerarrington** [comment]
Have we still not merged this ticket @iverc ?

**Comment by 59023g** [comment]
> Have we still not merged this ticket @iverc ?
No it did not follow confirmation modal standards.

**Comment by 59023g** [comment]
I will see if I can fix. @iverc @caseyturnerarrington

**Review by 59023g — APPROVED** [review]
Modal fixed. Will merge

**Pull request merged**
