### PR TITLE
refactors for code readability

### PR DESCRIPTION
**Pull request by Jedi2002**

### CODE REVIEW

**Review by iverc — DISMISSED** [review]

**Comment by Jedi2002** [comment]
@intl-man can you please let me know when develop is ready to start merging stuff again

**Review by intl-man — APPROVED** [review]

**Review by intl-man — APPROVED** [review]

**Review by iverc — APPROVED** [review]

**Review by iverc — APPROVED** [review]

**Comment by 59023g** [comment]
@Jedi2002 Will you include more detail on this PR? Are changes just formatting or are there functional changes here as well?

**Comment by Jedi2002** [comment]
> @Jedi2002 Will you include more detail on this PR? Are changes just formatting or are there functional changes here as well?

Hi @59023g  , This pr only has formating changes and code rearrangment , no functional changes

**Comment by intl-man** [comment]
@Jedi2002 This PR is quite stale. Are these changes still relevant?

**Comment by Jedi2002** [comment]
@intl-man @iverc  Closing this PR for now , but the changes are relevant and we might to revisit at some point in time

**Pull request closed without merging**
