### PR TITLE
Track Block Interest Payments in Pool

### PR DESCRIPTION
**Pull request by AustinoBombino**

### CODE REVIEW

**Review by timlind — APPROVED** [review]
LGTM.

**Comment by canercandan** [comment]
Pool state displays two new fields:
```
- block_interest_external: "0"
  block_interest_native: "0"
  external_asset:
    symbol: cusdc
  external_asset_balance: "610316557165"
  external_custody: "0"
  external_liabilities: "0"
  health: "0.000000000000000000"
  interest_rate: "0.000000000000000000"
  last_height_interest_rate_computed: "0"
  native_asset_balance: "81285119183944010790286697"
  native_custody: "0"
  native_liabilities: "0"
  pool_units: "81285119183944010790286697"
  reward_period_native_distributed: "0"
  swap_price_external: "133.185177805963498467"
  swap_price_native: "0.007508343018897287"
  unsettled_external_liabilities: "0"
  unsettled_native_liabilities: "0"
```

opened a usdc position against native token:
```
mtps:
- address: sif1syavy2npfyt9tcncdtsdzf7kny9lh777yqc2nd
  collateral_amount: "1000000000"
  collateral_asset: cusdc
  custody_amount: "1306449811787260977776612"
  custody_asset: rowan
  id: "1"
  interest_paid_collateral: "2331"
  interest_paid_custody: "304533521861470139"
  interest_unpaid_collateral: "0"
  leverage: "10.000000000000000000"
  liabilities: "9000000000"
  mtp_health: "1.086983729555555556"
  position: LONG
```

pool state displaying the calculated interest payment native asset, as opened position custody is native:
```
pools:
- block_interest_external: "0"
  block_interest_native: "14436273757179891"
  external_asset:
    symbol: cusdc
  external_asset_balance: "611316557165"
  external_custody: "0"
  external_liabilities: "9000000000"
  health: "0.985491278773643856"
  interest_rate: "0.000000018999999991"
  last_height_interest_rate_computed: "69"
  native_asset_balance: "79978669335203808238316299"
  native_custody: "1306449704658351628052378"
  native_liabilities: "0"
  pool_units: "81285119183944010790286697"
  reward_period_native_distributed: "0"
  swap_price_external: "131.038125777837119883"
  swap_price_native: "0.007631366780194997"
  unsettled_external_liabilities: "0"
  unsettled_native_liabilities: "0"
```

lets pick the pool state at height 122:

```
pools:
- block_interest_external: "0"
  block_interest_native: "26129002129615428"
  external_asset:
    symbol: cusdc
  external_asset_balance: "611316557165"
  external_custody: "0"
  external_liabilities: "9000000000"
  health: "0.985491278773643856"
  interest_rate: "0.000000022323891113"
  last_height_interest_rate_computed: "122"
  native_asset_balance: "79978670260464437180746845"
  native_custody: "1306448337458311688100189"
  native_liabilities: "0"
  pool_units: "81285119183944010790286697"
  reward_period_native_distributed: "0"
  swap_price_external: "131.038125065395373983"
  swap_price_native: "0.007631366821686008"
  unsettled_external_liabilities: "0"
  unsettled_native_liabilities: "0"
```

and lets pick the mtp object of the two consecutive block height (121 and 122):

```
caner@caner-ThinkPad-X1-Carbon-4th:~/Dev/sifchain/mngr (master)$ ./mtps.mjs -p localnet --height 122
$ sifnoded q margin positions-for-address sif1syavy2npfyt9tcncdtsdzf7kny9lh777yqc2nd $'--node=http://localhost:26657' $'--chain-id=localnet' $'--height=122' --count-total
mtps:
- address: sif1syavy2npfyt9tcncdtsdzf7kny9lh777yqc2nd
  collateral_amount: "1000000000"
  collateral_asset: cusdc
  custody_amount: "1306448337458311688100189"
  custody_asset: rowan
  id: "1"
  interest_paid_collateral: "13616"
  interest_paid_custody: "1778862471151146562"
  interest_unpaid_collateral: "0"
  leverage: "10.000000000000000000"
  liabilities: "9000000000"
  mtp_health: "1.086982533555555556"
  position: LONG
pagination:
  next_key: null
  total: "1"
caner@caner-ThinkPad-X1-Carbon-4th:~/Dev/sifchain/mngr (master)$ ./mtps.mjs -p localnet --height 121
$ sifnoded q margin positions-for-address sif1syavy2npfyt9tcncdtsdzf7kny9lh777yqc2nd $'--node=http://localhost:26657' $'--chain-id=localnet' $'--height=121' --count-total
mtps:
- address: sif1syavy2npfyt9tcncdtsdzf7kny9lh777yqc2nd
  collateral_amount: "1000000000"
  collateral_asset: cusdc
  custody_amount: "1306448363587313817715617"
  custody_asset: rowan
  id: "1"
  interest_paid_collateral: "13416"
  interest_paid_custody: "1752733469021531134"
  interest_unpaid_collateral: "0"
  leverage: "10.000000000000000000"
  liabilities: "9000000000"
  mtp_health: "1.086982554888888889"
  position: LONG
pagination:
  next_key: null
  total: "1"
```

Subtract interest_paid_custody values from each block:
```
1778862471151146562−1752733469021531134 = 26129002129615428
```

which is equals to:
```
block_interest_native: "26129002129615428"
```

**Comment by canercandan** [comment]
Opening 39 positions with 10x leverage:

```
pagination:
  next_key: null
  total: "39"
```

and the pool state block interest native value increases proportionally

```
- block_interest_external: "0"
  block_interest_native: "868892493888332784"
  external_asset:
    symbol: cusdc
  external_asset_balance: "649316557165"
  external_custody: "0"
  external_liabilities: "351000000000"
  health: "0.649111076402883805"
  interest_rate: "0.000000030657224438"
  last_height_interest_rate_computed: "751"
  native_asset_balance: "41500863421660030755624589"
  native_custody: "39784255176262718113222445"
  native_liabilities: "0"
  pool_units: "81285119183944010790286697"
  reward_period_native_distributed: "0"
  swap_price_external: "81.259395354099840852"
  swap_price_native: "0.012306269270677587"
  unsettled_external_liabilities: "0"
  unsettled_native_liabilities: "0"

```

**Comment by canercandan** [comment]
Opening a position in the opposite direction accrues the `block_interest_external` field value:

```pools:
- block_interest_external: "376"
  block_interest_native: "994727206529974710"
  external_asset:
    symbol: cusdc
  external_asset_balance: "637196315221"
  external_custody: "12120241944"
  external_liabilities: "351000000000"
  health: "0.631152961372272708"
  interest_rate: "0.000000034559171046"
  last_height_interest_rate_computed: "787"
  native_asset_balance: "41600897740117821668749769"
  native_custody: "39784220857804927200097265"
  native_liabilities: "900000000000000000000000"
  pool_units: "81285119183944010790286697"
  reward_period_native_distributed: "0"
  swap_price_external: "82.259078897111567904"
  swap_price_native: "0.012156712832279402"
  unsettled_external_liabilities: "0"
  unsettled_native_liabilities: "0"
```

**Review by canercandan — APPROVED** [review]
LGTM

**Pull request merged**
