### PR TITLE
Modify replay tests to use rowan so it goes through the symbol translation

### PR DESCRIPTION
**Pull request by banshee**
Any replays of ibc tokens or rowan need to go through the symbol translation code that was added for ibc.  This PR just modifies the replay test so it uses rowan instead of eth as the test currency.

### CODE REVIEW

**Review by ElliotFriedman — APPROVED** [review]
LGTM! Please hotfix up to testnet and master branches so that replaying can be done off master. Would appreciate if a file to translate rowan to erowan and vice versa could be included so that the users that run this can instantly pick it up out of the box and run things.

**Comment by banshee** [comment]
> LGTM! Please hotfix up to testnet and master branches so that replaying can be done off master. Would appreciate if a file to translate rowan to erowan and vice versa could be included so that the users that run this can instantly pick it up out of the box and run things.

The special case for rowan can be accomplished just using the translation file in test/integration/config/symbol_translator.json - that just has

```
$ cat config/symbol_translator.json 
{
  "ibc/FEEDFACEFEEDFACEFEEDFACEFEEDFACEFEEDFACEFEEDFACEFEEDFACEFEEDFACE": "Face",
  "rowan": "erowan"
}
```

Once we have actual ibc tokens, though, that test file isn't useful and we need the actual production symbol_translation file.

**Comment by banshee** [comment]
> Please hotfix up to testnet and master branches

Also, this PR doesn't actually add any new code; it just confirms what I had hoped, that all we needed to do was specify a --symbol-translator-file option to ebrelayer like this (a sample command from a test run, including unimportant/ephemeral keys to the test environment):

```
ebrelayer replayEthereum tcp://0.0.0.0:26657 ws://localhost:7545/ 0xf204a4Ef082f5c04bB89F7D5E6568B796096735a empty-mountain 'dish devote tag pipe flee sorry wheel science develop noise park service hungry spring nature check coral kit recycle mix luxury explain model shift' 225 277 1 2 --chain-id localnet --gas 5000000000000  --keyring-backend test --node tcp://0.0.0.0:26657 --from empty-mountain  --symbol-translator-file config/symbol_translator.json
```

**Review by khdegraaf — APPROVED** [review]
LGTM

**Review by ElliotFriedman — APPROVED** [review]

**Pull request merged**
