### PR TITLE
[ui] Feature/cross session peg notification

### PR DESCRIPTION
**Pull request by ryardley**
This listens for any pending transactions and surfaces those up to the store to be consumed by the view. 

To do this we:

* Get a list of tx hashes 
* Map them to a list of PegTxEmitters
* Connect the PegTxEmitters to the store and to the correct notification
* Read from the store in the view and add appropriate icon and tool tip with links to the block explorer

### CODE REVIEW

**Comment by caseyturnerarrington** [comment]
@ryardley whats the status of this PR? Still working through it?

**Comment by caseyturnerarrington** [comment]
Note: When I try to click on the link in the notification to the block explorer, it just closes the notification instead of opening the block explorer.

**Comment by ryardley** [comment]
> @ryardley whats the status of this PR? Still working through it?

This should be good to go once I update the merge conflicts and fix the click though issue you mentioned.

**Comment by ryardley** [comment]
@caseyturnerarrington I just restructured the close handlers on the tooltip to ensure it respects inner tooltip clicks.

**Review by thomasdavis — APPROVED** [review]

**Review by 59023g — APPROVED** [review]
🚀

**Pull request merged**
