### PR TITLE
Feature/pmtp unit tests

### PR DESCRIPTION
**Pull request by canercandan**

### CODE REVIEW

**Comment by AustinoBombino** [comment]
@canercandan we might want to merge this PR into feature/pmtp rather than develop

**Comment by canercandan** [comment]
> @canercandan we might want to merge this PR into feature/pmtp rather than develop

@AustinoBombino my bad just rebased the PR to `feature/pmtp` thanks

**Review by AustinoBombino — APPROVED** [review]
looks good

**Comment by marshsif** [comment]
reviewed and merged

**Pull request merged**
