### PR TITLE
[ui] Add snapshot and revert mechanism

### PR DESCRIPTION
**Pull request by ryardley**
## Instant Stack

This adds a new version of `yarn stack` which is based off snapshots. 

Time before backend can handle interaction (frontend still takes a bit of time for vue to compile)

| Before | Now | 
| --- | --- | 
|~90s | ~ 7s | 

Added snapshotting via  `yarn stack:save-snapshot` which will save to files in `./ui/chains/snapshots/*.tar.gz`

Rewrote `yarn stack` to run against snapshots so we don't need any configuration time. 

Running `yarn stack:backend` will restart backend services from snapshot state.

## Background 
This will speed up the dev cycle in many ways most of which are compounding. This should have a large impact on the productivity of our team.

1. Our tests now all run with deterministic state. It is getting closer to being fair to ask for some kind of test with every feature.
1. Once integrated local e2e tests will be MUCH quicker and easier to write by a large factor
2. local development will launch faster which means we can have faster development
3. We can fairly confidently expand our test coverage knowing that the state we use need not change 
4. Using named snapshots could mean we can setup a future system for complex state fixtures for exotic tests. 

## Todo
- [x] merge sifnoded hotfix
- [x] insta-stack running from snapshots
- [x] insta-stack saving snapshots
- [x] Work out why snapshots aren't working in CI
- [x] integration with playwright so we reset state every test
- [x] integration with our core stack backed tests so we reset state every test

## Notes

THERE IS LOTS OF CLEANUP

Ok this looks like it works but there is lots of clean up to do before this is neat. Happy to look at this at a later point but this will get us working with the ability to write tests which is the most important thing right now.

This gets us over the line and gets us but we need to revisit this and clean and optimize this. The following are tasks for the future.

1. Remove zip unpacking as it is superfluous now we are using docker
2. Don't build and compile anything we don't need to in CI (we don't need to build sifnoded for example as it is in the docker image which can be built elsewhere and just used)
3. Currently the image is hosted under @ryardley's dockerhub account this should change very soon to be built and hosted under our github actions account
4. There are lots of sleep calls and timeouts that are a little delicate here around ensuring that the stack has space to function correctly. Many of these can be fine tuned and should be revisited at a later point. This PR gets this working but we would be wise to slowly tune these in as we go.
5. We should move as a next step to parallel tests running in isolation. This should speed up our CI as there is overhead stopping and starting backing services and running everything in sequence.

#### Other notes

Getting this to work was far more challenging than I had expected. EBRelayer needs to stay synced with the blockchains or tests will fail. Everything needs to be shut down together and then restarted in the right order. In putting this together many other options were investigated:

* vagrant - was too difficult to share snapshots
* podman checkpoints - found it to be too particular around starting up and staying in sync with ebrelayer
* docker checkpoints - still in experimental mode

These approaches were taken with the false understanding that service state was memory only but it can actually run from disk which means a non-checkpoint container approach may be a good one in the future as it might be more scalable and increase starttime. Now after diving into this it is clear that blockchain state can be rebuilt from disk I can see a possibility to reorganize this again so we setup every e2e test in a parallel docker container that is a stage build from a set snapshot and set the command to run a single test on that container. This would mean we could run a docker container with separate state for every test and run those tests in parallel vastly speeding up CI. For now this works and pushes us forward allowing us to write more e2e tests so I would suggest getting this in and exploring whether docker can save time at a later point. 

I took the opportunity to re-organize the chains folder in a more scalable and hopefully understandable way.

### CODE REVIEW

**Comment by 59023g** [comment]
Looks super cool. Is there a specific Go version I need? I get `segementation violation`:
```
$ ./scripts/run-stack-backend.sh                                                                                                                                                            [216/216]
$ /Users/osso/sif/sifnode/ui/node_modules/.bin/concurrently -k -r -s first 'yarn chain:eth:revert' 'yarn chain:sif:revert' 'yarn wait-on http-get://localhost:1317/node_info tcp:localhost:7545 && ya
rn chain:peggy:revert'
$ cd ./chains/cosmos && ./revert.sh
$ /Users/osso/sif/sifnode/ui/node_modules/.bin/wait-on http-get://localhost:1317/node_info tcp:localhost:7545
$ cd ./chains/ethereum && ./revert.sh
Starting test chain
I[2021-04-12|16:21:54.153] Starting application REST service (chain-id: "sifchain-local")... module=rest-server
I[2021-04-12|16:21:54.153] Starting RPC HTTP server on 127.0.0.1:1317   module=rest-server
I[2021-04-12|16:21:54.246] Served RPC HTTP response                     module=rest-server method=GET url=/node_info status=500 duration=0 remoteAddr=127.0.0.1:60749
I[2021-04-12|16:21:54.267] Served RPC HTTP response                     module=rest-server method=GET url=/node_info status=500 duration=1 remoteAddr=127.0.0.1:60752
I[2021-04-12|16:21:54.275] starting ABCI with Tendermint                module=main
unexpected fault address 0x69726268746533c6
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x69726268746533c6 pc=0x104eab3b0]

goroutine 1 [running]:
runtime.throw(0x1052fa32a, 0x5)
        /opt/homebrew/Cellar/go/1.15.7_1/libexec/src/runtime/panic.go:1117 +0x54 fp=0x14000beec70 sp=0x14000beec40 pc=0x10484eed4
runtime.sigpanic()
        /opt/homebrew/Cellar/go/1.15.7_1/libexec/src/runtime/signal_unix.go:741 +0x230 fp=0x14000beecb0 sp=0x14000beec70 pc=0x104866890
github.com/golang/snappy.encodeBlock(0x14000f97502, 0x14da, 0x14da, 0x1400022ca00, 0x11c2, 0x2476, 0xf01)
        /Users/osso/go/pkg/mod/github.com/golang/snappy@v0.0.2/encode_arm64.s:666 +0x360 fp=0x14000bf6d50 sp=0x14000beecc0 pc=0x104eab3b0
github.com/golang/snappy.Encode(0x14000f97500, 0x14dc, 0x14dc, 0x0, 0x0, 0x0, 0x22a, 0x22a, 0x1400018ee68)
        /Users/osso/go/pkg/mod/github.com/golang/snappy@v0.0.2/encode.go:39 +0x17c fp=0x14000bf6da0 sp=0x14000bf6d50 pc=0x104eaa8ec
github.com/syndtr/goleveldb/leveldb/table.(*Writer).writeBlock(0x1400014c000, 0x1400014c058, 0x2, 0x0, 0x9, 0x10, 0x140000247e0)
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/table/writer.go:171 +0xb0 fp=0x14000bf6e20 sp=0x14000bf6da0 pc=0x104eb2ef0
github.com/syndtr/goleveldb/leveldb/table.(*Writer).finishBlock(0x1400014c000, 0x1400129bd4f, 0xc)
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/table/writer.go:222 +0x4c fp=0x14000bf6e70 sp=0x14000bf6e20 pc=0x104eb338c
github.com/syndtr/goleveldb/leveldb/table.(*Writer).Append(0x1400014c000, 0x1400129bd4f, 0xc, 0x3e42b1, 0x1400129bd5b, 0x22a, 0x3e42a5, 0x100, 0x1)
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/table/writer.go:255 +0x1e4 fp=0x14000bf6ee0 sp=0x14000bf6e70 pc=0x104eb35f4
github.com/syndtr/goleveldb/leveldb.(*tWriter).append(0x14000026360, 0x1400129bd4f, 0xc, 0x3e42b1, 0x1400129bd5b, 0x22a, 0x3e42a5, 0x0, 0x0)
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/table.go:559 +0xbc fp=0x14000bf6f50 sp=0x14000bf6ee0 pc=0x104ed4dac
github.com/syndtr/goleveldb/leveldb.(*tOps).createFrom(0x14001181740, 0x1058c72d8, 0x14001024000, 0x0, 0x0, 0x0, 0x0)                                                                       [183/216]
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/table.go:397 +0x11c fp=0x14000bf6ff0 sp=0x14000bf6f50 pc=0x104ed411c
github.com/syndtr/goleveldb/leveldb.(*session).flushMemdb(0x14001008ff0, 0x14001218000, 0x14000f84000, 0x0, 0x0, 0x0, 0x0)
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session_compaction.go:35 +0xa4 fp=0x14000bf7140 sp=0x14000bf6ff0 pc=0x104ecc404
github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal(0x14001216000, 0x14001216000, 0x140012143c0)
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:612 +0xa60 fp=0x14000bf7360 sp=0x14000bf7140 pc=0x104eb8370
github.com/syndtr/goleveldb/leveldb.openDB(0x14001008ff0, 0x0, 0x0, 0x14001008ff0)
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:131 +0x478 fp=0x14000bf7450 sp=0x14000bf7360 pc=0x104eb73e8
github.com/syndtr/goleveldb/leveldb.Open(0x1058c6088, 0x14000f57f10, 0x0, 0x0, 0x0, 0x0)
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:203 +0xd0 fp=0x14000bf74c0 sp=0x14000bf7450 pc=0x104eb7640
github.com/syndtr/goleveldb/leveldb.OpenFile(0x140011b4000, 0x29, 0x0, 0x140011b4000, 0x29, 0x14001191210)
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/db.go:225 +0x7c fp=0x14000bf7540 sp=0x14000bf74c0 pc=0x104eb782c
github.com/tendermint/tm-db.NewGoLevelDBWithOpts(0x105300c56, 0xb, 0x140011a8680, 0x1a, 0x0, 0x1064605b8, 0x140000ba680, 0x140011a8680)
        /Users/osso/go/pkg/mod/github.com/tendermint/tm-db@v0.5.1/goleveldb.go:31 +0xa4 fp=0x14000bf75b0 sp=0x14000bf7540 pc=0x104ee41c4
github.com/tendermint/tm-db.NewGoLevelDB(...)
        /Users/osso/go/pkg/mod/github.com/tendermint/tm-db@v0.5.1/goleveldb.go:26
github.com/tendermint/tm-db.init.0.func1(0x105300c56, 0xb, 0x140011a8680, 0x1a, 0x140000ba708, 0x10568e401, 0x1400021f728, 0x1049e7c24)
        /Users/osso/go/pkg/mod/github.com/tendermint/tm-db@v0.5.1/goleveldb.go:14 +0x44 fp=0x14000bf7600 sp=0x14000bf75b0 pc=0x104ee9e34
github.com/tendermint/tm-db.NewDB(0x105300c56, 0xb, 0x1052ff051, 0x9, 0x140011a8680, 0x1a, 0x140011a8680, 0x1a)
        /Users/osso/go/pkg/mod/github.com/tendermint/tm-db@v0.5.1/db.go:66 +0x180 fp=0x14000bf7710 sp=0x14000bf7600 pc=0x104ee3ea0
github.com/cosmos/cosmos-sdk/types.NewLevelDB(0x105300c56, 0xb, 0x140011a8680, 0x1a, 0x0, 0x0, 0x0, 0x0)
        /Users/osso/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.2/types/utils.go:84 +0x88 fp=0x14000bf7780 sp=0x14000bf7710 pc=0x104f52d18
github.com/cosmos/cosmos-sdk/server.openDB(0x140000dc558, 0x15, 0xb, 0x0, 0x0, 0x1)
        /Users/osso/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.2/server/constructors.go:29 +0x88 fp=0x14000bf77f0 sp=0x14000bf7780 pc=0x105232398
github.com/cosmos/cosmos-sdk/server.startInProcess(0x1400012b0e0, 0x105876ab8, 0x1d, 0x0, 0x0)
        /Users/osso/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.2/server/start.go:162 +0x90 fp=0x14000bf7c40 sp=0x14000bf77f0 pc=0x1052338f0
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0x14001027b80, 0x10608b0c0, 0x0, 0x0, 0x0, 0x0)
        /Users/osso/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.2/server/start.go:82 +0xa4 fp=0x14000bf7c90 sp=0x14000bf7c40 pc=0x105235ba4
github.com/spf13/cobra.(*Command).execute(0x14001027b80, 0x10608b0c0, 0x0, 0x0, 0x14001027b80, 0x10608b0c0)
        /Users/osso/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x320 fp=0x14000bf7d50 sp=0x14000bf7c90 pc=0x104e2ef40
github.com/spf13/cobra.(*Command).ExecuteC(0x1400101c000, 0x1, 0x140010330e0, 0x105323cdf)
        /Users/osso/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x258 fp=0x14000bf7e30 sp=0x14000bf7d50 pc=0x104e2f7a8
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/osso/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895                                                                                                                 [150/216]
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x1400101c000, 0x105876f18, 0x105305fe2, 0x10)
        /Users/osso/go/pkg/mod/github.com/tendermint/tendermint@v0.33.9/libs/cli/setup.go:89 +0x38 fp=0x14000bf7ec0 sp=0x14000bf7e30 pc=0x104e91c38
main.main()
        /Users/osso/sif/sifnode/cmd/sifnoded/main.go:69 +0x6b8 fp=0x14000bf7f70 sp=0x14000bf7ec0 pc=0x1052f2d18
runtime.main()
        /opt/homebrew/Cellar/go/1.15.7_1/libexec/src/runtime/proc.go:225 +0x26c fp=0x14000bf7fd0 sp=0x14000bf7f70 pc=0x10485137c
runtime.goexit()
        /opt/homebrew/Cellar/go/1.15.7_1/libexec/src/runtime/asm_arm64.s:1130 +0x4 fp=0x14000bf7fd0 sp=0x14000bf7fd0 pc=0x1048863e4

goroutine 38 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x14000f76460)
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:209 +0xcc
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/util/buffer_pool.go:240 +0x15c

goroutine 39 [select]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0x14001008ff0)
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session_util.go:189 +0x390
created by github.com/syndtr/goleveldb/leveldb.newSession
        /Users/osso/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca/leveldb/session.go:93 +0x224
I[2021-04-12|16:21:54.506] Served RPC HTTP response                     module=rest-server method=GET url=/node_info status=500 duration=1 remoteAddr=127.0.0.1:60756
I[2021-04-12|16:21:54.513] Served RPC HTTP response                     module=rest-server method=GET url=/node_info status=500 duration=0 remoteAddr=127.0.0.1:60760
[1/4] 🔍  Resolving packages...
success Already up-to-date.
I[2021-04-12|16:21:54.751] Served RPC HTTP response                     module=rest-server method=GET url=/node_info status=500 duration=0 remoteAddr=127.0.0.1:60768
I[2021-04-12|16:21:54.761] Served RPC HTTP response                     module=rest-server method=GET url=/node_info status=500 duration=0 remoteAddr=127.0.0.1:60772
$ /Users/osso/sif/sifnode/ui/chains/ethereum/node_modules/.bin/ganache-cli -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --db /Users/osso/.ganachedb -p 7545 --netw
orkId 5777 -g 20000000000 --gasLimit 6721975
I[2021-04-12|16:21:55.006] Served RPC HTTP response                     module=rest-server method=GET url=/node_info status=500 duration=0 remoteAddr=127.0.0.1:60776
```

**Comment by 59023g** [comment]
I think if `save-snapshot-from-scripts` was named, `save-default-snapshot` it'd be more descriptive. The concept of `default` makes sense here. And perhaps some sort of future notation to describe scenarios will need to be developed.

**Comment by ryardley** [comment]
Hey @59023g any chance you can check if you get the same error you were having before? I didn't attempt to fix it as I couldn't replicate but I believe this should now work so would be good to check if there are version issues or anything like that.

**Comment by 59023g** [comment]
> .. check if you get the same error you were having before

Yes. I get the one where where the RPC is looking for `/node_info` while incrementing ports.
image

But `yarn stack:save-default-snapshot` looks good

**Comment by ryardley** [comment]
So I did actually have go1.14 running on my MacBook. I ported my whole system to linux ensured I have built sifnoded with go1.15 and I still don't have any issues at all with this branch. I used gvm and ran go 1.15 and things worked as expected out of the box. 

```
$ go version 
go version go1.15 linux/amd64

$ yarn chain:build && yarn stack:backend
...
```

could this be something like chip architecture?

**Comment by ryardley** [comment]
I noticed a couple of scripts were missing a shebang - I fixed that not sure if it is related as I cannot reproduce.

**Comment by ryardley** [comment]
Ok this looks like it works but there is lots of clean up to do before this is neat. Happy to look at this at a later point but this will get us working with the ability to write tests which is the most important thing right now.

This gets us over the line and gets us but we need to revisit this and clean and optimize this. The following are tasks for the future.

1. Remove zip unpacking as it is superfluous now we are using docker
2. Don't build and compile anything we don't need to in CI (we don't need to build sifnoded for example as it is in the docker image which can be built elsewhere and just used)
3. Currently the image is hosted under @ryardley's dockerhub account this should change very soon to be built and hosted under our github actions account
4. There are lots of sleep calls and timeouts that are a little delicate here around ensuring that the stack has space to function correctly. Many of these can be fine tuned and should be revisited at a later point. This PR gets this working but we would be wise to slowly tune these in as we go.
5. We should move as a next step to parallel tests running in isolation. This should speed up our CI as there is overhead stopping and starting backing services and running everything in sequence.

**Review by 59023g — APPROVED** [review]
Bravo  🌹

**Review by 59023g — APPROVED** [review]

**Review by 59023g — APPROVED** [review]

**Pull request merged**
