### PR TITLE
feat: min validator commission

### PR DESCRIPTION
**Pull request by dgtizestake**
# Description

This adds a custom AnteDecorator which enforces a minimum commission of 5% for validators. The check is performed for the following msg types:
* MsgCreateValidator
* MsgEditValidator
* MsgDelegate
* MsgBeginRedelegate
* ~~MsgWithdrawDelegatorReward~~

## Additional Notes 

- ~~If a delegator wants to withdraw delegation rewards from a non-compliant validator, they are still able to get their rewards either by undelegating or redelegating to a compliant validator. Refer to the [BeforeDelegationSharesModified](https://github.com/cosmos/cosmos-sdk/blob/33dbf6a795e68c744a2c312b76d41614b3563c01/x/distribution/keeper/hooks.go#L85) hook, which is called during [Unbond](https://github.com/cosmos/cosmos-sdk/blob/33dbf6a795e68c744a2c312b76d41614b3563c01/x/staking/keeper/delegation.go#L640).~~
- ~~However, if the delegator is within the 21 days redelegation period, they would be unable to redelegate and hence locked out of rewards claim for that time, short of undelegating. Perhaps better to remove the MsgWithdrawDelegatorReward check then.~~
- Out of 266 validators queried, the following 2 have a **max. commission** less than the proposed 5% minimum, which will make them bricked. One of these validators is in the active set. We will need to deal with this edge case. Approach taken by Osmosis [found here](https://github.com/osmosis-labs/osmosis/blob/b71507c04b970780013b00b2420290245a238604/app/upgrades/v3/forks.go#L31) courtesy of @BlockNgine. **If the team supports this approach I can add it to the PR?** 

| max_rate  | moniker | operator_address | active | 
| ------------- | ------------- | ------------- | ------------- | 
| 0.02  | unizen | sifvaloper12s6szauzsjmr84n4yuury3dtns3m84s5yvxy3j | yes |
| 0.02 | Medions  | sifvaloper1lrt2yj75fm3w2730yypfwjkdap0wcwgscqdn7l | no |

- Furthermore, the following validators have a current commission rate and max. daily change rate which would prevent them from becoming compliant (5% commission) in a **single edit validator tx**:

| rate | max_change_rate  | moniker | operator_address | active |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 0.03 | 0.01 | feles | sifvaloper1xnfkccy79fnhnl2le8nxn6kfnrl7qycvmtgcl0 | no |
| 0 | 0.01 | Spring. 0% to 2023 | sifvaloper1xavn8dny5yd2w4t455geysnsju4fszxv4909q6 | yes |
| 0.02 | 0.01 |  polkachu.com  | sifvaloper1gp957czryfgyvxwn3tfnyy2f0t9g2p4pfj2j90 | yes |
| 0.01 | 0.02 | unizen | sifvaloper12s6szauzsjmr84n4yuury3dtns3m84s5yvxy3j | yes |
| 0.01 | 0.01 | Binance validator | sifvaloper1v33fa93vt0elqcgdngzu6pu5qgsdk03ynq6pcj | no |
| 0.03 | 0.01 | Samurai Vikings | sifvaloper1va8dlzuuwzf4tpnkzues2cdwvze5m6q9aqhf45 | yes |
| 0 | 0.01 | nullnodes | sifvaloper1su0n5e8x6n5zwhc05m599nuwe2ahpnmdly29ey | no |
| 0.03 | 0.01 | humble_staking | sifvaloper1jygg7lyzu490y3ja8637ktr53vxv6dk9kuqfaj | no |
| 0.01 | 0.01 | sifstake.prxy | sifvaloper15zqdf7svujgnvp909uzuyn4yxpc4htxc4f03zx | no |
| 0.02 | 0.01 | StakeLab | sifvaloper1kttxh8lxsmez56pen3cw307raf45fj9vmvwn5j | yes |
| 0.02 | 0.01 | SmartNodes | sifvaloper1hz9rznf0dp5j9gk449969hr2y550pxsnxqfav6 | yes |
| 0.02 | 0.01 | Winter Validator. | sifvaloper1cl2dlphuceygxec7mmez905clvn4pw9d793m55 | yes |
| 0 | 0.01 | 0% Fee to 2023  Stakewolle.com | sifvaloper1ecv3sdx8h54ckv8q8u67cyk0nj37rffwpj7cdx | yes |
| 0.03 | 0.01 | Sir Francis Node  100% Carbon Compensated | sifvaloper1m73gste7wsx5gup55z6p7s52yas0njk6g3zhmh | yes |
| 0.01 | 0.01 | itokenpool | sifvaloper1u5kng6hdd5vmr4j35qskp0zsvtwxpquvkfl68t | no |
| 0.03 | 0.01 | GATA validators | sifvaloper1u453cen62m939v548nfql54zl886a9zy7ggzqq | yes |
| 0.01 | 0.01 | itokenpool | sifvaloper1a2nc2nuyzles9kcwaq4ay7hfkxtapqsd94dcg0 | no |
| 0.03 | 0.01 |   | sifvaloper17hwgtya6snf38j06gsketqprrfpwgzwf9eg3xx | no |
| 0.02 | 0.02 | Medions | sifvaloper1lrt2yj75fm3w2730yypfwjkdap0wcwgscqdn7l | no |

- - - 

## Author Checklist

I have...

- [x]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x]  added ! to the type prefix if API or client breaking change
- [x]  targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ]  provided a link to the relevant issue or specification
- [x]  followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
- [ ]  included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- [ ]  added a changelog entry to CHANGELOG.md
- [x]  included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ]  updated the relevant documentation or specification
- [ ]  reviewed "Files changed" and left comments if necessary
- [ ]  confirmed all CI checks have passed

## Reviewer Checklist
All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  confirmed ! in the type prefix if API or client breaking change
- [ ]  confirmed all author checklist items have been addressed
- [ ]  reviewed state machine logic
- [ ]  reviewed API design and naming
- [ ]  reviewed documentation is accurate
- [ ]  reviewed tests and test coverage
- [ ]  manually tested (if applicable)

### CODE REVIEW

**Comment by BlockNgine** [comment]
Excellant, thankyou!
My thoughts:

1. `MsgEditValidator` needs to allow for a validator to be able to increment up to the 5%, for example if a validator has 2% commission and a `--commission-max-change-rate=0.01` their validator can only increase commission by 1% every 24h so they will become effectively bricked as they can't increment all the way to the minimum.

1. We need a blocker on `MsgBeginRedelegate` to prevent people redelegating from 5% validators to 0%

2. Remove `MsgWithdrawDelegatorReward` as that unfairly punishes delegators of validators who are in the process of moving to the minimum commission but can't instantly because of daily limit set by `--commission-max-change-rate`.
And as ou already pointed out in Discord if a validator is mid re-delegation already then they are completely out of options

**Comment by dgtizestake** [comment]
> Excellant, thankyou! My thoughts:
> 
> 1. `MsgEditValidator` needs to allow for a validator to be able to increment up to the 5%, for example if a validator has 2% commission and a `--commission-max-change-rate=0.01` their validator can only increase commission by 1% every 24h so they will become effectively bricked as they can't increment all the way to the minimum.
> 2. We need a blocker on `MsgBeginRedelegate` to prevent people redelegating from 5% validators to 0%
> 3. Remove `MsgWithdrawDelegatorReward` as that just punishes delegators of validators who are in the process of moving to the minimum commission but can't instantly because of daily limit set by `--commission-max-change-rate`.
>    And as ou already pointed out in Discord if a validator is mid re-delegation already then they are completely out of options

I added the check on MsgBeginRedelegate and removed it on MsgWithdrawDelegatorReward. I'll wait for the team's thoughts on the fork approach for max. daily change and max. commission below the minimum before implementing it.

**Comment by BlockNgine** [comment]
Well I guess one solution to mitigate bricking validators and if we don't want to fork just yet is to apply a 1% minimum commission for now?

**Comment by Jedi2002** [comment]
The PR looks great. 

A possible way to deal with validators getting bricked is to iterate over the validator set and, set the commission rate for every validator to 5%.

**Comment by dgtizestake** [comment]
> The PR looks great.
> 
> A possible way to deal with validators getting bricked is to iterate over the validator set and, set the commission rate for every validator to 5%.

In terms of implementation, are we ok with Osmosis' approach? https://github.com/osmosis-labs/osmosis/blob/b71507c04b970780013b00b2420290245a238604/app/upgrades/v3/forks.go#L31

**Comment by Jedi2002** [comment]
> > The PR looks great.
> > A possible way to deal with validators getting bricked is to iterate over the validator set and, set the commission rate for every validator to 5%.
> 
> In terms of implementation, are we ok with Osmosis' approach? https://github.com/osmosis-labs/osmosis/blob/b71507c04b970780013b00b2420290245a238604/app/upgrades/v3/forks.go#L31

Yup ! That looks good to me

**Comment by BlockNgine** [comment]
I found another commit to demonstrate how to implement

https://github.com/CosmosContracts/juno/pull/81/files

**Comment by BlockNgine** [comment]
some test code here: https://github.com/terra-money/core/pull/47/files#diff-d6dbb138ad19332d23445b91c0d08b123a065f6fe8d05e1c94e0ab42962fd672 (app/ante/min_commission_test.go) 
but would also need testing on a localnet/testnet

**Pull request closed without merging**
