### PR TITLE
deploy/scripts/entrypoint.sh: rest-server --unsafe-cors

### PR DESCRIPTION
**Pull request by 59023g**
Wasn't sure if change should be in `deploy/helm/sifnode/templates/sifnodecli-deployment.yaml`

Resolves https://github.com/Sifchain/sifnode/issues/298

### CODE REVIEW

**Comment by utx0** [comment]
doh, we just change the process setup method under your feet. We might just do this in another PR.

**Comment by 59023g** [comment]
> doh, we just change the process setup method under your feet. We might just do this in another PR.
Like tears in the rain...

**Comment by 59023g** [comment]
Will alter tomorrow

**Comment by intl-man** [comment]
@59023g this has been done in PR #302 .

**Pull request closed without merging**
