### PR TITLE
Feature/pmtp unit test coverage

### PR DESCRIPTION
**Pull request by canercandan**
~81% code coverage

### CODE REVIEW

**Review by AustinoBombino — APPROVED** [review]
@canercandan These tests look great!

One thing to add would be cases for swaps and liquidity removes that have `pmtpCurrentRunningRate`'s other than 1.0 so we can make sure the calcs are behaving as expected.

We'll need to get/come up with sample values for those cases.

**Comment by canercandan** [comment]
> @canercandan These tests look great!
> 
> One thing to add would be cases for swaps and liquidity removes that have `pmtpCurrentRunningRate`'s other than 1.0 so we can make sure the calcs are behaving as expected.
> 
> We'll need to get/come up with sample values for those cases.

@AustinoBombino just added more use cases to cover behavior and expected outputs for all the possible values of `pmtpCurrentRunningRate` between `0.0` to `1.0` with `0.1` increments, let me know if that what you had in mind or if there are any other assessments that need to be done. Thanks for your feedback

**Comment by marshsif** [comment]
pmtpCurrentRunningRate range should be 0 thru 10, decimal format.

**Comment by canercandan** [comment]
@AustinoBombino just updated the branch cover all the values for pmtp current running rate from 0 to 10 with 1.0 increments.

**Comment by AustinoBombino** [comment]
@canercandan nice! looks good to me

**Pull request merged**
