### PR TITLE
[Github Actions] Feature/Vercel GitHub Action Autodeploy

### PR DESCRIPTION
**Pull request by 59023g**
This will auto deploy pushes to `/ui` directory to a Vercel alias with `{{BRANCH}}.sifchain.vercel.app` URL

### CODE REVIEW

**Comment by 59023g** [comment]
I've tested workflow working locally with [act](https://github.com/nektos/act). Not sure how to test it live. Please advise

**Review by ryardley — APPROVED** [review]

**Comment by 59023g** [comment]
@ryardley I added the config changes so this would work on deploy

**Review by utx0 — CHANGES_REQUESTED** [review]
It would be good to have two deploy targets setup. One for the sandpit env as this is where we are going to do all internal testing, then another for merry-go-round for the public. 

Sandpit will also get updated much more often from the `develop` branch too .

**Comment by utx0** [comment]
Hey @59023g are you still working on this? I can see you made some of the changes but its also failing the ci steps now. Great to get this online as soon as we can. Thanks mate

**Comment by 59023g** [comment]
> Hey @59023g are you still working on this? I can see you made some of the changes but its also failing the ci steps now. Great to get this online as soon as we can. Thanks mate

Still working on it! Will only deploy against sandpit for now. Was waiting on the sandpit faucet to be ready (why I deployed against MGR first).

**Comment by 59023g** [comment]
Ok. This is now pointed at `sandpit` and has incorporated @ryardley architecture changes related to RE ABI contract (I do believe we should fetch it remotely when in prod but that's a separate discussion). 

Please review @utx0

**Review by utx0 — APPROVED** [review]
Prefect!

**Pull request merged**
