### PR TITLE
Fix for amino/ledger support for unbonding liquidity

### PR DESCRIPTION
**Pull request by timlind**

### CODE REVIEW

**Review by AustinoBombino — APPROVED** [review]

**Review by Jedi2002 — APPROVED** [review]

**Comment by arno01** [comment]
@timlind is it too early to try this PR?

Am currently getting 111222 rc. Possibly because it requires RPC node to run with this patch?

```
$ sifnoded tx clp unbond-liquidity --symbol udvpn --units 1 --fees 100000000000000000rowan --from default --sign-mode amino-json -y
code: 111222
codespace: undefined
data: ""
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'panic message redacted to hide potentially sensitive system info: panic'
timestamp: ""
tx: null
txhash: [redacted]
```

**Comment by timlind** [comment]
@arno01 running the node with this patch should resolve the panic there.

> @timlind is it too early to try this PR?
> 
> Am currently getting 111222 rc. Possibly because it requires RPC node to run with this patch?
>

**Comment by arno01** [comment]
> @arno01 running the node with this patch should resolve the panic there.
> 
> > @timlind is it too early to try this PR?
> > Am currently getting 111222 rc. Possibly because it requires RPC node to run with this patch?

Have updated my validator to run with this patch, got over the 111222 rc.

But now am getting this error:

```
$ export SIFNODED_GAS=300000
$ export SIFNODED_GAS_PRICES=$(echo "0.0034*10^14" | bc)rowan
$ export SIFNODED_CHAIN_ID=sifchain-1
$ export SIFNODED_NODE=http://127.0.0.1:26657

$ sifnoded tx clp unbond-liquidity --symbol ibc/21CB41565FCA19AB6613EE06B0D56E588E0DC3E53FF94BA499BB9635794A1A35 --units 1 --from default --sign-mode amino-json

{"body":{"messages":[{"@type":"/sifnode.clp.v1.MsgUnlockLiquidityRequest","signer":"REDACTED","external_asset":{"symbol":"ibc/21CB41565FCA19AB6613EE06B0D56E588E0DC3E53FF94BA499BB9635794A1A35"},"units":"1"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"rowan","amount":"102000000000000000"}],"gas_limit":"300000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
code: 4
codespace: sdk
data: ""
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'signature verification failed; please verify account number (REDACTED), sequence
  (508) and chain-id (sifchain-1): unauthorized'
timestamp: ""
tx: null
txhash: REDACTED
```

account_number - matches
sequence - it says 507, however when am using Sifchain UI (web version) it always tries to use 506 sequence for `clp/UnlockLiquidity` msgs.type.

```
$ sifnoded query account REDACTED
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "REDACTED"
address: REDACTED
pub_key:
  '@type': /cosmos.crypto.secp256k1.PubKey
  key: REDACTED
sequence: "507"
```

Now sure where is the truth though, any hint what could I try?

**Comment by timlind** [comment]
@arno01 sorry for the miscommunication, we're aiming to get a release out in the next week including this, so yes it is too soon.

That error looks unrelated, you can file an issue with our support team.

**Comment by arno01** [comment]
> 

thanks, @timlind 
I've created the issue via Discord reg. the account sequence number in Sifchain UI.  TIcket: `#ticket-289`.

**Pull request merged**
