### PR TITLE
Implemented Azure AKS support for sifnode

### PR DESCRIPTION
**Pull request by stevo1403**
Sifnode can now be successfully deployed on Microsoft Azure using terraform.

### CODE REVIEW

**Comment by intl-man** [comment]
@stevo1403 - thanks for your work on this, we do appreciate it. We've actually moved all our DevOps effort into a new repository. We're also making a number of changes to our rake tasks, so we'll incorporate your changes into another PR over there.

**Comment by stevo1403** [comment]
Hi @intl-man, Is the $1000 USDC bounty still valid?

**Comment by stevo1403** [comment]
Fixes #503

**Comment by stevo1403** [comment]
Closes #503

**Pull request closed without merging**
