### PR TITLE
Feature/clp asymetric liquidity

### PR DESCRIPTION
**Pull request by Jedi2002**

### CODE REVIEW

**Comment by ryardley** [comment]
This sounds like something that is error prone should we add an automated test somewhere for this?

**Comment by Jedi2002** [comment]
> This sounds like something that is error prone should we add an automated test somewhere for this?

We do have the unit tests covering this . The testing team is working on some integration tests ,that should cover the the automation part when its done .
Also , i think the test table that you suggested might help flesh out more issues . I can probably create some sort of a suite around it.

**Comment by ryardley** [comment]
> We do have the unit tests covering this 

Ah my bad!

**Review by ryardley — APPROVED** [review]

**Comment by utx0** [comment]
So @Jedi2002 @ryardley what was the issue that this change was resolving?

**Comment by Jedi2002** [comment]
> So @Jedi2002 @ryardley what was the issue that this change was resolving?

This change allows for completely asymetric add liquidity , you can issue trasactions like 1000rowan ,0ceth . 
Earlier we did not allow 0 value of a token .

**Comment by utx0** [comment]
> > So @Jedi2002 @ryardley what was the issue that this change was resolving?
> 
> This change allows for completely asymetric add liquidity , you can issue trasactions like 1000rowan ,0ceth .
> Earlier we did not allow 0 value of a token .@utxo

Sweet, I just found and read the ticket for this too. Great work. Once the test pass ill merge it in.

**Review by utx0 — APPROVED** [review]

**Pull request merged**
