### PR TITLE
[Peggy] Integration tests now run in parallel

### PR DESCRIPTION
**Pull request by banshee**

### CODE REVIEW

**Review by khdegraaf — APPROVED** [review]

**Comment by banshee** [comment]
On the github action run, these hung at the "integration-tests Expected — Waiting for status to be reported" stage.  Tests have completed, but github is having issues cleaning up.

**Comment by banshee** [comment]
The tests pass, but then the github action doesn't complete.  Let's not do this for now.

**Comment by khdegraaf** [comment]
I see these tests completing successfully...

**Comment by khdegraaf** [comment]
restoring and re-opening to investigate supposed failure.

**Pull request merged**
